"use strict";
const $=id=>document.getElementById(id),audio=$('music'),reduced=matchMedia('(prefers-reduced-motion: reduce)');
function syncMusic(){$('music-button').textContent=audio.paused?'♫':'Ⅱ';$('music-button').setAttribute('aria-label',audio.paused?'Reproducir música':'Pausar música');$('music-button').setAttribute('aria-pressed',String(!audio.paused))}audio.addEventListener('play',syncMusic);audio.addEventListener('pause',syncMusic);$('music-button').onclick=()=>audio.paused?audio.play().catch(syncMusic):audio.pause();
$('open').onclick=()=>{$('open').disabled=true;audio.volume=.55;audio.play().catch(syncMusic);$('cover').classList.add('opening');setTimeout(()=>{$('cover').hidden=true;$('invitation').hidden=false;$('music-button').hidden=false;scrollTo(0,0);document.querySelector('.hero h1').focus({preventScroll:true});if(!reduced.matches&&'IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.06});document.querySelectorAll('.reveal').forEach(el=>{el.classList.add('waiting');observer.observe(el)})}},reduced.matches?0:1250)};
for(let i=0;i<34;i++){const day=i-2,cell=document.createElement('span');if(day>0){cell.textContent=day;if(day===24){cell.className='chosen';cell.setAttribute('aria-label','24 de octubre, nuestra boda')}}$('calendar-days').append(cell)}
const target=Date.parse('2026-10-24T10:00:00-04:00');function tick(){const t=Math.max(0,Math.floor((target-Date.now())/1000));[Math.floor(t/86400),Math.floor(t/3600)%24,Math.floor(t/60)%60,t%60].forEach((v,i)=>$(['days','hours','minutes','seconds'][i]).textContent=String(v).padStart(2,'0'))}tick();setInterval(tick,1000);
$('church-map').href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent('Iglesia Nuestra Señora de la Inmaculada Concepción Laja Bolivia');
$('confirm').href='https://wa.me/59172922183?text='+encodeURIComponent('Hola, confirmo mi asistencia a la boda de Luis y Ariana el 24 de octubre.\nMi nombre: \nNúmero de asistentes: ');$('confirm').hidden=false;$('rsvp-pending').hidden=true;
document.querySelectorAll('.artist').forEach(button=>button.onclick=()=>{$('large-photo').src=button.dataset.photo;$('large-photo').alt=button.dataset.title;$('large-title').textContent=button.dataset.title;$('lightbox').showModal();document.body.style.overflow='hidden'});$('close').onclick=()=>$('lightbox').close();$('lightbox').addEventListener('close',()=>document.body.style.overflow='');$('lightbox').addEventListener('click',e=>{if(e.target===$('lightbox')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});
for(let i=0;i<20;i++){const dot=document.createElement('i');dot.style.cssText=`--x:${i*37%100}%;--y:${i*53%100}%;--duration:${4+i%5}s;--delay:${-i*.7}s`;$('sparkles').append(dot)}document.addEventListener('visibilitychange',()=>document.querySelectorAll('#sparkles i').forEach(el=>el.style.animationPlayState=document.hidden?'paused':'running'));
