"use strict";
const $=id=>document.getElementById(id),audio=$('music'),reduced=matchMedia('(prefers-reduced-motion: reduce)');
function syncMusic(){$('music-button').textContent=audio.paused?'♫':'Ⅱ';$('music-button').setAttribute('aria-label',audio.paused?'Reproducir música':'Pausar música');$('music-button').setAttribute('aria-pressed',String(!audio.paused))}audio.addEventListener('play',syncMusic);audio.addEventListener('pause',syncMusic);$('music-button').onclick=()=>audio.paused?audio.play().catch(syncMusic):audio.pause();
$('open').onclick=()=>{$('open').disabled=true;audio.volume=.55;audio.play().catch(syncMusic);$('cover').classList.add('opening');setTimeout(()=>{$('cover').hidden=true;$('invitation').hidden=false;$('music-button').hidden=false;scrollTo(0,0);document.querySelector('.hero h1').focus({preventScroll:true});if(!reduced.matches&&'IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.06});document.querySelectorAll('.reveal').forEach(el=>{el.classList.add('waiting');observer.observe(el)})}},reduced.matches?0:1250)};
for(let i=0;i<34;i++){const day=i-2,cell=document.createElement('span');if(day>0){cell.textContent=day;if(day===24){cell.className='chosen';cell.setAttribute('aria-label','24 de octubre, nuestra boda')}}$('calendar-days').append(cell)}
const target=Date.parse('2026-10-24T09:30:00-04:00');function tick(){const t=Math.max(0,Math.floor((target-Date.now())/1000));[Math.floor(t/86400),Math.floor(t/3600)%24,Math.floor(t/60)%60,t%60].forEach((v,i)=>$(['days','hours','minutes','seconds'][i]).textContent=String(v).padStart(2,'0'))}tick();setInterval(tick,1000);
$('church-map').href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent('Iglesia Nuestra Señora de la Inmaculada Concepción Laja Bolivia');
$('confirm').href='https://wa.me/59172922183?text='+encodeURIComponent('Hola, confirmo mi asistencia a la boda de Luis y Ariana el 24 de octubre.\nMi nombre: \nNúmero de asistentes: ');$('confirm').hidden=false;$('rsvp-pending').hidden=true;
document.querySelectorAll('.artist').forEach(button=>button.onclick=()=>{$('large-photo').src=button.dataset.photo;$('large-photo').alt=button.dataset.title;$('large-title').textContent=button.dataset.title;$('lightbox').showModal();document.body.style.overflow='hidden'});$('close').onclick=()=>$('lightbox').close();$('lightbox').addEventListener('close',()=>document.body.style.overflow='');$('lightbox').addEventListener('click',e=>{if(e.target===$('lightbox')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});
for(let i=0;i<20;i++){const dot=document.createElement('i');dot.style.cssText=`--x:${i*37%100}%;--y:${i*53%100}%;--duration:${4+i%5}s;--delay:${-i*.7}s`;$('sparkles').append(dot)}document.addEventListener('visibilitychange',()=>document.querySelectorAll('#sparkles i').forEach(el=>el.style.animationPlayState=document.hidden?'paused':'running'));

// Tres vuelos continuos; cada punto de la estela desaparece en 2,6 segundos.
const flightCanvas=$('flight-canvas'),flightCtx=flightCanvas.getContext('2d');
let flightWidth=0,flightHeight=0,flightFrame=0,lastFlightTime=0,flightClock=0,lastDot=0;
const flightTrails=[[],[],[]],planeShape=new Path2D('M58 6c-3-3-7-1-10 2L35 21 9 16 4 21l22 10-12 13-9-1-4 4 14 5 5 11 4-4-1-10 13-12 10 22 5-5-5-26L58 15c3-4 3-7 0-9z');
function resizeFlights(){const scale=Math.min(devicePixelRatio||1,2);flightWidth=innerWidth;flightHeight=innerHeight;flightCanvas.width=Math.round(flightWidth*scale);flightCanvas.height=Math.round(flightHeight*scale);flightCtx.setTransform(scale,0,0,scale,0,0);flightTrails.forEach(t=>t.length=0)}
function flightPoint(t,i){const phase=t/14000+i*Math.PI*2/3;return {x:flightWidth*(.5+.42*Math.sin(phase)),y:flightHeight*(.5+.36*Math.sin(phase*.8+i*1.4))}}
function drawFlights(now){flightFrame=0;if(reduced.matches||document.hidden)return;const delta=lastFlightTime?Math.min(50,now-lastFlightTime):0;lastFlightTime=now;flightClock+=delta;flightCtx.clearRect(0,0,flightWidth,flightHeight);const add=flightClock-lastDot>100;if(add)lastDot=flightClock;
 for(let i=0;i<3;i++){const point=flightPoint(flightClock,i),ahead=flightPoint(flightClock+30,i),trail=flightTrails[i];if(add)trail.push({...point,time:flightClock});while(trail.length&&flightClock-trail[0].time>2600)trail.shift();
  for(const dot of trail){const opacity=(1-(flightClock-dot.time)/2600)*.65;flightCtx.globalAlpha=opacity;flightCtx.fillStyle=i?'#71846b':'#b69a58';flightCtx.beginPath();flightCtx.arc(dot.x,dot.y,1.7,0,Math.PI*2);flightCtx.fill()}
  flightCtx.save();flightCtx.globalAlpha=.88;flightCtx.translate(point.x,point.y);flightCtx.rotate(Math.atan2(ahead.y-point.y,ahead.x-point.x)+Math.PI/4);flightCtx.scale(.42,.42);flightCtx.translate(-32,-32);flightCtx.fillStyle=i?'#617854':'#c3a260';flightCtx.strokeStyle='#f7edce';flightCtx.lineWidth=1.5;flightCtx.fill(planeShape);flightCtx.stroke(planeShape);flightCtx.restore()
 }flightCtx.globalAlpha=1;flightFrame=requestAnimationFrame(drawFlights)}
function syncFlights(){if(flightFrame)cancelAnimationFrame(flightFrame);flightFrame=0;lastFlightTime=0;if(!reduced.matches&&!document.hidden)flightFrame=requestAnimationFrame(drawFlights);else flightCtx.clearRect(0,0,flightWidth,flightHeight)}
resizeFlights();syncFlights();addEventListener('resize',resizeFlights);document.addEventListener('visibilitychange',syncFlights);reduced.addEventListener('change',syncFlights);
